
name: Deploy YAML files in sequence - first yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: '*'
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job deploys the first YAML file
  deploy-first:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Build and test
          run: |
            echo "Building and testing"
        - name: Call second workflow
          uses: ./.github/workflows/terraform.yml
          #with:
          #  arg1: value1
          #  arg2: value2