name: run npm
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: npm init
        - name: npm ci
          run: npm ci
        - name: npm build
          run: npm run build --if-present
        - name: npm test
          run: npm test