name: run npm
on:
  push:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        - name: Initiate npm
          run: |
            npm ci
            npm run build --if-present
            npm test

        - name: install npm
          run: npm install
        #- name: npm ci
        #  run: npm ci
        - name: npm build
          run: npm run build --if-present
        #- name: npm test
        #  run: npm test