name: upload website
on: 
    push:
        branches:
            # Here we choose to deploy only when a push is detect on the main branch
            - main

jobs:
    # Jobs define the functionality that will be run in the workflow and run in parallel by default
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:

            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ap-southeast-1 #update S3 bucket region here
          
            # Installs AWS CLI version 2
        - name: Install AWS CLI v2
          run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update #update flag worked

        # Syncs the repo with the S3 bucket
        - name: Sync with S3
          run: |
            aws s3 sync /index.html
            

        # this does not deploy -  i need to create a s3 myself first, this doesn't do anything?
        #- name: Deploy static website to S3 bucket
        #  run: aws s3 sync . s3://test-enchen --delete #update bucketname here
    deploy:
        runs-on: ubuntu-latest
        needs: build  
        steps:
        - name: Upload to S3
          uses: actions/checkout@master

        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: test-enchen
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-southeast-1'   # optional: defaults to us-east-1
            SOURCE_DIR: 'public'      # optional: defaults to entire repository